name: API Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set API key
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python quote.py > output.txt

      - name: Update README.md
        run: |
          output=$(cat output.txt)
          sed -i "s/<!-- START_SECTION:output -->.*<!-- END_SECTION:output -->/<!-- START_SECTION:output -->\n${output}\n<!-- END_SECTION:output -->/" README.md
        if: always()
        
      - name: View output file
        run: cat output.txt
