name: API Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set API key
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python quote.py > output.txt
          
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: output

      - name: Update README.md
        run: |
          echo "```" > temp.txt
          cat output.txt >> temp.txt
          echo "```" >> temp.txt
          sed -i -e '/<!--START_SECTION:output-->/r temp.txt' -e '/<!--END_SECTION:output-->/d' README.md
        if: always()
        
      - name: View output file
        run: cat output.txt
